{% set name = "scikit-gstat" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d4f0c959d9ed3aa608df3529e7d6354ad27463b21d8c1fe65d87aa917e35d19

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - imageio
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - python
    - scikit-learn
    - scipy

test:
  imports:
    - skgstat
    - skgstat.data
    - skgstat.interfaces
    - skgstat.plotting
    - skgstat.tests
    - skgstat.util

about:
  home: https://github.com/mmaelicke/scikit-gstat
  license: MIT
  license_file: LICENSE
  summary: Geostatistical expansion in the scipy style
  doc_url: https://mmaelicke.github.io/scikit-gstat/
  dev_url: https://github.com/mmaelicke/scikit-gstat

extra:
  recipe-maintainers:
    - mmaelicke
    - erikmannerfelt
