{% set name = "scikit-gstat" %}
{% set version = "1.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9271290154a421dd8b08ddc514a2c69e8083d64a4d81202b6c52b5104825e739

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - imageio
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - python
    - scikit-learn
    - scipy
    - joblib
    - tqdm

test:
  imports:
    - skgstat
    - skgstat.data
    - skgstat.interfaces
    - skgstat.plotting
    - skgstat.tests
    - skgstat.util

about:
  home: https://github.com/mmaelicke/scikit-gstat
  license: MIT
  license_file: LICENSE
  summary: Geostatistical expansion in the scipy style
  doc_url: https://mmaelicke.github.io/scikit-gstat/
  dev_url: https://github.com/mmaelicke/scikit-gstat

extra:
  recipe-maintainers:
    - mmaelicke
    - erikmannerfelt
